"""Is speculative throughput bimodal, and does that depend on the draft mechanism?

Reads `results/probes.jsonl`, written by the `boot_variance` probe, and
reports per (mechanism, arm, concurrency) how far apart the boots of an
identical configuration landed.

The question this exists to answer is the biggest generalisability gap in
the paper. F020 and F021 establish the bimodality entirely on DFlash, so a
reviewer can reasonably ask whether it is a property of that draft model
rather than of speculative decoding on this engine. `ngram` uses
prompt-lookup and loads no draft checkpoint at all, so a bimodal result
there places the effect on the speculative verification path.

**Bimodality is not variance.** A wide unimodal spread and two tight modes
look identical in a standard deviation, and reading one as the other is the
error F020 made and F021 corrected. So this reports the spread *and* a
crude separation test: sort the boots, find the largest adjacent gap, and
ask whether that gap is large relative to the scatter within the resulting
groups. With a handful of boots this cannot be conclusive, and it says so
rather than printing a verdict it cannot support.

    python analysis/boot_modes.py
"""

from __future__ import annotations

import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROBES = ROOT / "results" / "probes.jsonl"
OUT = ROOT / "analysis" / "out" / "tables"

#: A split is only worth reporting if the gap between groups is at least
#: this multiple of the within-group scatter. Deliberately blunt.
SEPARATION = 3.0


def split_at_largest_gap(values: list[float]):
    """Partition sorted values at their largest adjacent gap.

    Returns (low, high, gap, within) or None when there are too few points.
    `within` is the larger of the two groups' ranges, so the comparison is
    against the worst-behaved group rather than an average.
    """
    if len(values) < 4:
        return None
    v = sorted(values)
    gaps = [(v[i + 1] - v[i], i) for i in range(len(v) - 1)]
    gap, idx = max(gaps)
    low, high = v[: idx + 1], v[idx + 1:]
    within = max(max(low) - min(low), max(high) - min(high))
    return low, high, gap, within


def main() -> int:
    if not PROBES.exists():
        print(f"no {PROBES.relative_to(ROOT)} yet — run the boot_variance "
              f"probe first", file=sys.stderr)
        return 1

    runs: dict[tuple, list[float]] = defaultdict(list)
    taus: dict[tuple, list[float]] = defaultdict(list)
    for line in PROBES.read_text().splitlines():
        if not line.strip():
            continue
        try:
            r = json.loads(line)
        except json.JSONDecodeError:
            continue
        if r.get("phase") != "boot_variance":
            continue
        if (r.get("outcome") or {}).get("status") not in ("ok", "partial"):
            continue
        cfg, load = r.get("config") or {}, r.get("load") or {}
        key = (cfg.get("mechanism"), r.get("arm"), load.get("concurrency"))
        tput = (r.get("throughput") or {}).get("output_tokens_per_s")
        if tput:
            runs[key].append(tput)
        tau = (r.get("spec") or {}).get("tau")
        if tau:
            taus[key].append(tau)

    if not runs:
        print("probes.jsonl has no boot_variance measurements", file=sys.stderr)
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    L = ["# Boot-to-boot modes by draft mechanism", "",
         "*Generated by `analysis/boot_modes.py` from `results/probes.jsonl`. "
         "Do not edit by hand.*", "",
         "Each row is repeated boots of one identical configuration. "
         "`spread` is max/min. A **split** is reported only when the largest "
         "gap between sorted boots is at least "
         f"{SEPARATION:g}x the scatter within the resulting groups — a wide "
         "unimodal spread and two tight modes are indistinguishable in a "
         "standard deviation, and confusing them is the error F020 made.", "",
         "| mechanism | arm | conc | boots | min | max | spread | tau spread | split? |",
         "|---|---|---|---|---|---|---|---|---|"]

    for key in sorted(runs, key=lambda k: (str(k[0]), str(k[1]), k[2] or 0)):
        vals = runs[key]
        if len(vals) < 2:
            continue
        mech, arm, conc = key
        spread = max(vals) / min(vals)
        tv = taus.get(key) or []
        tau_spread = (f"{max(tv) / min(tv):.3f}x" if len(tv) > 1 else "-")

        verdict = "too few boots"
        s = split_at_largest_gap(vals)
        if s is not None:
            low, high, gap, within = s
            if within > 0 and gap / within >= SEPARATION:
                verdict = (f"**yes** — {len(low)} near "
                           f"{statistics.mean(low):.0f}, {len(high)} near "
                           f"{statistics.mean(high):.0f}")
            elif within == 0:
                verdict = "**yes** — groups are single points"
            else:
                verdict = f"no (gap {gap / within:.1f}x within-group)"

        L.append(f"| {mech} | {arm} | {conc} | {len(vals)} | {min(vals):.1f} | "
                 f"{max(vals):.1f} | {spread:.2f}x | {tau_spread} | {verdict} |")

    L += ["", "## Reading this", "",
          "A mechanism whose **default** arm splits while its acceptance "
          "(tau) does not is showing the F021 effect. A mechanism whose "
          "default arm does not split — with enough boots to have seen it — "
          "would place the effect on the draft model rather than on the "
          "engine's speculative path.", "",
          "With few boots per row, 'no' means 'not demonstrated here', not "
          "'absent'. The slow mode was observed in roughly one draw in three "
          "for DFlash, so a three-boot row has a material chance of missing "
          "it entirely."]

    (OUT / "boot_modes.md").write_text("\n".join(L) + "\n")
    print(f"  wrote analysis/out/tables/boot_modes.md ({len(runs)} groups)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
