"""Regenerate findings/README.md from the finding files' frontmatter.

Hand-maintained indexes drift. This one is derived, so a finding that exists
is listed and a listing that exists has a finding.
"""
from __future__ import annotations
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FIND = ROOT / "findings"

ORDER = {"result": 0, "method": 1, "gap": 2, "retraction": 3}


def parse(path: Path) -> dict:
    text = path.read_text()
    m = re.match(r"^---\n(.*?)\n---\n", text, re.DOTALL)
    meta: dict = {"file": path.name}
    if not m:
        return meta
    for line in m.group(1).split("\n"):
        mm = re.match(r"^(\w+):\s*(.*)$", line)
        if mm and mm.group(2).strip():
            meta[mm.group(1)] = mm.group(2).strip()
    return meta


def main() -> None:
    items = [parse(p) for p in sorted(FIND.glob("F*.md"))]
    L = ["# Findings",
         "",
         "*Generated by `analysis/build_index.py`. Do not edit by hand.*",
         "",
         "Every claim this study makes, with the evidence behind it and the",
         "limits on it. Schema and rules: [`docs/data-model.md`](../docs/data-model.md).",
         "",
         "Findings are append-only. A claim that turns out to be wrong is marked",
         "`retracted` and kept, because how a result was arrived at — including the",
         "wrong turns and what caught them — is part of the evidence.",
         ""]
    for kind, heading in (("result", "Results"), ("method", "Method"),
                          ("gap", "Known gaps"), ("retraction", "Retractions")):
        rows = [i for i in items if i.get("kind") == kind]
        if not rows:
            continue
        L += [f"## {heading}", "",
              "| id | claim | status | confidence |", "|---|---|---|---|"]
        for i in rows:
            L.append(f"| [`{i.get('id','?')}`]({i['file']}) | {i.get('title','?')} "
                     f"| {i.get('status','?')} | {i.get('confidence','–')} |")
        L.append("")
    counts = {k: sum(1 for i in items if i.get("kind") == k) for k in ORDER}
    L += ["---", "",
          f"{len(items)} findings: " +
          ", ".join(f"{v} {k}" for k, v in counts.items() if v) + ".", ""]
    (FIND / "README.md").write_text("\n".join(L))
    print(f"  wrote findings/README.md ({len(items)} findings)")


if __name__ == "__main__":
    main()
