"""Regenerate every derived table in analysis/out/tables from results/.

No GPU, no network, deterministic. Run after any new results land:

    python analysis/build_tables.py

Each table carries a header naming this script, its input, and the code SHA, so
a number in the paper can be traced to the commit that produced it. These files
are committed but never hand-edited: a wrong number here means a wrong script.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

RESULTS = ROOT / "results"
OUT = ROOT / "analysis" / "out" / "tables"


def code_sha() -> str:
    try:
        return subprocess.run(
            ["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:
        return "unknown"


def header(title: str, inputs: list[str]) -> str:
    return (
        f"# {title}\n\n"
        f"*Generated by `analysis/build_tables.py` from "
        f"{', '.join(f'`{i}`' for i in inputs)} at code "
        f"`{code_sha()}`. Do not edit by hand.*\n\n"
    )


def latest_cells() -> dict[str, dict]:
    """Last record per cell_id — cells.jsonl is append-only with supersession."""
    latest: dict[str, dict] = {}
    with open(RESULTS / "cells.jsonl") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            latest[rec["cell_id"]] = rec
    return latest


def write(name: str, text: str) -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / name).write_text(text)
    print(f"  wrote analysis/out/tables/{name}")


def t_runs() -> None:
    runs = json.load(open(RESULTS / "runs.json"))["runs"]
    L = [header("Runs", ["results/runs.json"])]
    L.append("| run_id | sweep | GPU | engine | cells | GPU-s | statuses |")
    L.append("|---|---|---|---|---|---|---|")
    for r in runs:
        st = ", ".join(f"{k}={v}" for k, v in r["status_counts"].items())
        L.append(
            f"| `{r['run_id']}` | `{Path(r['sweep']).name}` | {r['gpu']} "
            f"(SM{str(r['compute_cap']).replace('.','')}) | {r['engine']} "
            f"{r['engine_version']} | {r['n_unique_cells']} | "
            f"{r['gpu_seconds']:.0f} | {st} |"
        )
    total = sum(r["gpu_seconds"] for r in runs)
    L.append(f"\nTotal GPU time across all runs: **{total:.0f} s "
             f"({total/3600:.2f} h)**.\n")
    L.append("\nAll three runs are `reconstructed: true` — boundaries were "
             "inferred from timestamp gaps because they predate live run "
             "manifests.\n")
    write("runs.md", "\n".join(L))


def t_compat() -> None:
    cells = latest_cells()
    L = [header("Compatibility matrix (latest record per cell)",
                ["results/cells.jsonl"])]
    L.append("`status` is the probe verdict; `ok` requires both a successful "
             "boot and a passing correctness verdict.\n")
    L.append("| model | mech | weight | kv_cache | attn_backend | status | "
             "tau | accept | KV tokens | cell_id |")
    L.append("|---|---|---|---|---|---|---|---|---|---|")
    rows = sorted(cells.values(), key=lambda r: (
        r["config"]["model"], r["config"]["mechanism"],
        r["config"]["weight_precision"], r["config"]["kv_cache_dtype"],
        r["config"].get("attn_backend", "auto")))
    for r in rows:
        c, sp = r["config"], (r.get("spec") or {})
        cap = (r.get("capacity") or {}).get("kv_tokens_max")
        f = lambda v: "–" if v is None else v
        L.append(
            f"| {c['model'].split('/')[-1]} | {c['mechanism']} | "
            f"{c['weight_precision']} | {c['kv_cache_dtype']} | "
            f"{c.get('attn_backend','auto')} | {r['outcome']['status']} | "
            f"{f(sp.get('tau'))} | {f(sp.get('acceptance_rate'))} | "
            f"{f(cap)} | `{r['cell_id'][:8]}` |")
    write("compatibility_matrix.md", "\n".join(L) + "\n")


def t_backend() -> None:
    from specfp8.analysis.backend_report import analyse, format_report
    rows = analyse(RESULTS)
    L = [header("Attention backend actually used, per cell",
                ["results/cells.jsonl", "results/logs/"])]
    L.append("`actual` is parsed from the engine's own startup log, not "
             "inferred. `None` means no persisted log exists (cells run "
             "before log persistence) or no backend line matched.\n")
    L.append("```\n" + format_report(rows) + "\n```\n")
    write("backend_attribution.md", "\n".join(L))


def t_correctness() -> None:
    from specfp8.analysis.correctness_matrix import analyse, format_report
    L = [header("Tests 1 and 2 — matched-pair correctness",
                ["results/cells.jsonl", "results/requests/"])]
    for model in ("Qwen/Qwen3-4B", "Qwen/Qwen3-0.6B"):
        res = analyse(RESULTS, model=model)
        if not res["test1"] and not res["test2"]:
            continue
        L.append(f"\n## {model}\n")
        L.append("```\n" + format_report(res) + "\n```\n")
    write("correctness_tests.md", "\n".join(L))


def t_capacity() -> None:
    cells = latest_cells()
    idx = {}
    for r in cells.values():
        c = r["config"]
        cap = (r.get("capacity") or {}).get("kv_tokens_max")
        if cap and r["outcome"]["status"] == "ok":
            idx[(c["model"], c["mechanism"], c["weight_precision"],
                 c.get("attn_backend", "auto"), c["kv_cache_dtype"])] = cap
    L = [header("KV cache capacity gain from FP8 KV",
                ["results/cells.jsonl"])]
    L.append("Measured, not computed from a formula (R8). Ratio is "
             "`fp8_e4m3 / auto` holding model, mechanism, weights and backend "
             "fixed.\n")
    L.append("**`attn_backend: auto` rows are not backend-controlled and their "
             "ratio is not a clean FP8 effect.** vLLM selects FlashAttention-2 "
             "at BF16 KV and switches to FlashInfer when FP8 KV is requested, "
             "so those two columns are different backends and the ratio mixes "
             "the precision change with a backend change. Read the explicit "
             "backend rows instead.\n")
    L.append("| model | mech | weight | backend | BF16 KV | FP8 KV | ratio |")
    L.append("|---|---|---|---|---|---|---|")
    seen = sorted({k[:4] for k in idx})
    for key in seen:
        a, b = idx.get((*key, "auto")), idx.get((*key, "fp8_e4m3"))
        if a and b:
            flag = "" if key[3] != "auto" else "  ⚠ backend differs between columns"
            L.append(f"| {key[0].split('/')[-1]} | {key[1]} | {key[2]} | "
                     f"{key[3]} | {a:,} | {b:,} | **{b/a:.3f}x**{flag} |")
    controlled = [b / a for key in seen
                  if key[3] != "auto"
                  and (a := idx.get((*key, "auto"))) and (b := idx.get((*key, "fp8_e4m3")))]
    if controlled:
        L.append(f"\nBackend-controlled rows only: ratio ranges "
                 f"**{min(controlled):.3f}x – {max(controlled):.3f}x** "
                 f"(n={len(controlled)}), against a theoretical 2.000x for "
                 f"16-bit to 8-bit KV.")
    write("kv_capacity.md", "\n".join(L) + "\n")


def main() -> None:
    print(f"Regenerating tables from {RESULTS} at code {code_sha()}")
    for fn in (t_runs, t_compat, t_backend, t_correctness, t_capacity):
        try:
            fn()
        except Exception as e:
            print(f"  FAILED {fn.__name__}: {type(e).__name__}: {e}")


if __name__ == "__main__":
    main()
