"""Paired comparison of the CUDA-graph arms, per configuration.

perf_v2 carries `enforce_eager` as an axis, so every configuration appears
twice: once with CUDA graphs on (engine default) and once off. This pairs
those two by everything-except-the-flag and reports the ratio.

Pairing matters more than it sounds. The two arms are separate boots, and
F021 establishes that a speculative boot lands in one of two modes and stays
there, so a default-arm number is one draw from a bimodal distribution.
Comparing arm means across *different* configurations would mix that
lottery with the effect under study; comparing the same configuration to
itself does not remove the lottery but at least isolates it to one term.

It also tests the prediction pre-registered in docs/paper-outline.md before
the grid ran:

  1. With graphs off, all four speculative cells land in fast mode and the
     bf16 rows rise from ~30 to roughly 70-80 tok/s.
  2. The FP8-weight advantage survives but shrinks from ~3x to ~1.2-1.4x.
  3. The fp8-weight rows move least, being in fast mode already.

The script prints the prediction alongside the measurement and does not
adjust either to fit the other.

    python analysis/cudagraph_arms.py
"""

from __future__ import annotations

import json
import statistics
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "results"
OUT = ROOT / "analysis" / "out" / "tables"

#: Config fields that define a pair. Deliberately everything that identifies
#: a ServerCell EXCEPT enforce_eager -- that is the axis being compared.
PAIR_FIELDS = ("engine", "engine_ref", "model", "model_revision", "mechanism",
               "draft_model", "draft_revision", "weight_precision",
               "kv_cache_dtype", "attn_backend", "spec_tokens", "block_size",
               "guided_decoding")


def sha() -> str:
    try:
        return subprocess.run(
            ["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def load() -> list[dict]:
    path = RESULTS / "sweep.jsonl"
    if not path.exists():
        return []
    latest: dict[str, dict] = {}
    for line in path.read_text().splitlines():
        if line.strip():
            r = json.loads(line)
            latest[r["run_id"]] = r      # later supersedes earlier
    return list(latest.values())


def pair_key(cfg: dict) -> tuple:
    return tuple(cfg.get(f) for f in PAIR_FIELDS)


def mean(vals) -> float | None:
    vals = [v for v in vals if v is not None]
    return statistics.mean(vals) if vals else None


def main() -> int:
    runs = load()
    if not runs:
        print("No sweep results yet.", file=sys.stderr)
        return 1

    # (config-without-eager, concurrency) -> {eager_bool: [records]}
    cells: dict[tuple, dict[bool, list[dict]]] = defaultdict(
        lambda: defaultdict(list))
    for r in runs:
        cfg = r["config"]
        eager = bool(cfg.get("enforce_eager", False))
        cells[(pair_key(cfg), r["load"]["concurrency"])][eager].append(r)

    paired = {k: v for k, v in cells.items() if len(v) == 2}
    unpaired = {k: v for k, v in cells.items() if len(v) != 2}

    OUT.mkdir(parents=True, exist_ok=True)
    L = ["# CUDA-graph arms, paired by configuration", "",
         f"*Generated by `analysis/cudagraph_arms.py` from "
         f"`results/sweep.jsonl` at code `{sha()}`. Do not edit by hand.*", "",
         "`graphs on` is the engine default; `graphs off` is "
         "`--enforce-eager`. Each arm is a separate boot, so a speculative "
         "`graphs on` figure is one draw from the bimodal distribution of "
         "findings/F021, not a stable mean.", "",
         "| mech | weights | kv | conc | graphs on | graphs off | off/on | "
         "tau on | tau off |",
         "|---|---|---|---|---|---|---|---|---|"]

    def label(rs):
        c = rs[0]["config"]
        return (c["mechanism"], c["weight_precision"], c["kv_cache_dtype"])

    rows = []
    for (pk, conc), arms in sorted(
            paired.items(), key=lambda kv: (label(kv[1][False] or kv[1][True]),
                                            kv[0][1])):
        on = mean([r["throughput"]["output_tokens_per_s"] for r in arms[False]])
        off = mean([r["throughput"]["output_tokens_per_s"] for r in arms[True]])
        tau_on = mean([(r.get("spec") or {}).get("tau") for r in arms[False]])
        tau_off = mean([(r.get("spec") or {}).get("tau") for r in arms[True]])
        mech, wp, kv = label(arms[False] or arms[True])
        ratio = off / on if (on and off) else None
        rows.append({"mech": mech, "weights": wp, "kv": kv, "conc": conc,
                     "on": on, "off": off, "ratio": ratio,
                     "tau_on": tau_on, "tau_off": tau_off})
        L.append(
            f"| {mech} | {wp} | {kv} | {conc} | "
            f"{on:.1f} | {off:.1f} | "
            f"{f'**{ratio:.2f}x**' if ratio else '-'} | "
            f"{f'{tau_on:.3f}' if tau_on else '-'} | "
            f"{f'{tau_off:.3f}' if tau_off else '-'} |")

    if unpaired:
        L += ["", "> **Unpaired cells.** These configurations appear in only "
              "one arm, so no ratio is computable. Usually means the grid is "
              "still running or a cell failed to boot.", ""]
        for (pk, conc), arms in sorted(unpaired.items(), key=str):
            rs = arms.get(False) or arms.get(True)
            mech, wp, kv = label(rs)
            have = "graphs on" if False in arms else "graphs off"
            L.append(f"> - {mech}/{wp}/{kv} c={conc}: only {have}")

    # --- the pre-registered prediction, checked ---
    L += ["", "## Pre-registered prediction (docs/paper-outline.md)", "",
          "Recorded before this grid ran. Reported as measured either way.", ""]

    spec1 = [r for r in rows if r["mech"] != "none" and r["conc"] == 1]
    bf16 = [r for r in spec1 if r["weights"] == "bf16"]
    fp8 = [r for r in spec1 if r["weights"] == "fp8"]

    def verdict(ok: bool | None) -> str:
        return {True: "**HOLDS**", False: "**FAILS**",
                None: "insufficient data"}[ok]

    # 1. bf16 speculative rows rise to ~70-80 with graphs off
    p1 = None
    if bf16:
        offs = [r["off"] for r in bf16 if r["off"]]
        p1 = bool(offs) and all(60 <= v <= 95 for v in offs)
        L.append(f"1. bf16 speculative c=1 reaches ~70-80 tok/s with graphs "
                 f"off: {verdict(p1)} "
                 f"(measured {', '.join(f'{v:.1f}' for v in offs)})")
    else:
        L.append(f"1. bf16 speculative c=1 rises to ~70-80: {verdict(None)}")

    # 2. FP8-weight advantage shrinks from ~3x to ~1.2-1.4x
    p2 = None
    if bf16 and fp8:
        a_on = mean([r["on"] for r in fp8]) / mean([r["on"] for r in bf16])
        a_off = mean([r["off"] for r in fp8]) / mean([r["off"] for r in bf16])
        p2 = a_off < a_on and 1.1 <= a_off <= 1.6
        L.append(f"2. FP8-weight advantage shrinks to ~1.2-1.4x: "
                 f"{verdict(p2)} (graphs on {a_on:.2f}x -> "
                 f"graphs off {a_off:.2f}x)")
    else:
        L.append(f"2. FP8-weight advantage shrinks: {verdict(None)}")

    # 3. fp8-weight rows move least between arms
    p3 = None
    if bf16 and fp8:
        m_bf = mean([r["ratio"] for r in bf16 if r["ratio"]])
        m_fp = mean([r["ratio"] for r in fp8 if r["ratio"]])
        p3 = m_fp < m_bf
        L.append(f"3. fp8-weight rows move least between arms: "
                 f"{verdict(p3)} (bf16 {m_bf:.2f}x vs fp8 {m_fp:.2f}x)")
    else:
        L.append(f"3. fp8-weight rows move least: {verdict(None)}")

    if p2 is False:
        L += ["", "> If the FP8-weight gap did **not** shrink, the mode story "
              "does not explain the split: FP8 weights genuinely carry a "
              "large speculative advantage and F020's withdrawal of the "
              "interaction was too aggressive. That is a result, not a "
              "failure of the experiment."]

    (OUT / "cudagraph_arms.md").write_text("\n".join(L) + "\n")
    print(f"  wrote analysis/out/tables/cudagraph_arms.md "
          f"({len(paired)} paired, {len(unpaired)} unpaired)")
    for n, p in (("1", p1), ("2", p2), ("3", p3)):
        print(f"    prediction {n}: {verdict(p).replace('**', '')}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
