"""Goodput under an SLO, computed offline from stored per-request timings.

Goodput is successful requests per second that *also* met a latency target.
Raw tokens/sec flatters a server that is fast on average while missing its
deadline, which is why R7 asks for goodput rather than throughput.

Everything here derives from `results/runs/<run_id>.jsonl`, so adding an SLO
after the fact costs no GPU. That is the whole reason Phase 2 stores every
request instead of aggregates.

    python analysis/goodput.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
RESULTS = ROOT / "results"
OUT = ROOT / "analysis" / "out" / "tables"

#: Swept rather than fixed (R7), so the conclusion's sensitivity to the
#: threshold is visible instead of hidden inside one arbitrary choice.
ITL_SLOS_MS = [20, 35, 50, 75]
TTFT_SLOS_MS = [200, 500, 1000]


def percentile(values: list[float], q: float) -> float | None:
    """Nearest-rank percentile. No numpy dependency for one number."""
    if not values:
        return None
    ordered = sorted(values)
    k = max(0, min(len(ordered) - 1, int(round(q * (len(ordered) - 1)))))
    return ordered[k]


def load_runs() -> list[dict]:
    path = RESULTS / "sweep.jsonl"
    if not path.exists():
        return []
    out = []
    with open(path) as f:
        for line in f:
            if line.strip():
                out.append(json.loads(line))
    # Later records supersede earlier ones for the same measurement.
    latest: dict[str, dict] = {}
    for r in out:
        latest[r["run_id"]] = r
    return list(latest.values())


def load_requests(run_id: str) -> list[dict]:
    path = RESULTS / "runs" / f"{run_id}.jsonl"
    if not path.exists():
        return []
    with open(path) as f:
        return [json.loads(l) for l in f if l.strip()]


def goodput(requests: list[dict], wall_s: float,
            itl_slo_ms: float, ttft_slo_ms: float) -> dict:
    """Requests/sec that succeeded AND met both latency targets."""
    met = 0
    for r in requests:
        if not r.get("ok"):
            continue
        itls = r.get("itl_ms") or []
        p95 = percentile(itls, 0.95)
        # A request with no inter-token samples produced at most one token;
        # judge it on TTFT alone rather than discarding or failing it.
        if p95 is not None and p95 > itl_slo_ms:
            continue
        if r.get("ttft_ms", 0) > ttft_slo_ms:
            continue
        met += 1
    return {
        "met": met,
        "total": len(requests),
        "goodput_rps": round(met / wall_s, 4) if wall_s else None,
        "met_fraction": round(met / len(requests), 4) if requests else None,
    }


def main() -> None:
    runs = load_runs()
    if not runs:
        print("No sweep results yet. Run: python -m specfp8.sweep "
              "--sweep sweeps/perf.yaml")
        return

    OUT.mkdir(parents=True, exist_ok=True)
    rows = []
    for rec in runs:
        reqs = load_requests(rec["run_id"])
        wall = rec["throughput"]["wall_clock_s"]
        cfg, load = rec["config"], rec["load"]
        for itl in ITL_SLOS_MS:
            for ttft in TTFT_SLOS_MS:
                g = goodput(reqs, wall, itl, ttft)
                rows.append({
                    "mechanism": cfg["mechanism"],
                    "weight_precision": cfg["weight_precision"],
                    "kv_cache_dtype": cfg["kv_cache_dtype"],
                    "attn_backend": cfg.get("attn_backend", "auto"),
                    "workload": load["workload"],
                    "concurrency": load["concurrency"],
                    "itl_slo_ms": itl,
                    "ttft_slo_ms": ttft,
                    "goodput_rps": g["goodput_rps"],
                    "met_fraction": g["met_fraction"],
                    "throughput_rps": rec["throughput"]["requests_per_s"],
                    "output_tokens_per_s": rec["throughput"]["output_tokens_per_s"],
                })

    header = list(rows[0].keys())
    csv = [",".join(header)]
    csv += [",".join("" if r[k] is None else str(r[k]) for k in header)
            for r in rows]
    (OUT / "goodput.csv").write_text("\n".join(csv) + "\n")
    print(f"  wrote analysis/out/tables/goodput.csv "
          f"({len(rows)} rows from {len(runs)} measurements)")

    # A readable slice at one SLO; the CSV carries the full sweep.
    ref = [r for r in rows if r["itl_slo_ms"] == 50 and r["ttft_slo_ms"] == 1000]
    md = ["# Goodput at p95 ITL <= 50ms, TTFT <= 1000ms", "",
          "*Generated by `analysis/goodput.py` from `results/sweep.jsonl` and "
          "`results/runs/`. Full SLO sweep in `goodput.csv`.*", "",
          "| mech | weights | kv | conc | goodput req/s | met | raw req/s | tok/s |",
          "|---|---|---|---|---|---|---|---|"]
    for r in sorted(ref, key=lambda r: (r["mechanism"], r["weight_precision"],
                                        r["kv_cache_dtype"], r["concurrency"])):
        md.append(
            f"| {r['mechanism']} | {r['weight_precision']} | "
            f"{r['kv_cache_dtype']} | {r['concurrency']} | "
            f"{r['goodput_rps']} | {r['met_fraction']} | "
            f"{r['throughput_rps']} | {r['output_tokens_per_s']} |")
    (OUT / "goodput.md").write_text("\n".join(md) + "\n")
    print("  wrote analysis/out/tables/goodput.md")


if __name__ == "__main__":
    main()
