"""Performance tables from the Phase 2 sweep.

Aggregates the three repeats per cell into a mean and a spread, because a
single measurement at low concurrency is unreliable: repeats draw different
prompts, and at 16 prompts the draw moves throughput by tens of percent.

Also checks that every measurement at a given concurrency used the same
number of requests. Request count is derived in code rather than being part
of a RunCell's identity, so a change to the formula cannot invalidate old
records through the staleness check -- it has to be caught here instead.
"""

from __future__ import annotations

import json
import statistics
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
RESULTS = ROOT / "results"
OUT = ROOT / "analysis" / "out" / "tables"


def sha() -> str:
    try:
        return subprocess.run(["git", "-C", str(ROOT), "rev-parse", "--short", "HEAD"],
                              capture_output=True, text=True, check=True).stdout.strip()
    except Exception:
        return "unknown"


def load() -> dict[str, dict]:
    path = RESULTS / "sweep.jsonl"
    latest: dict[str, dict] = {}
    if not path.exists():
        return latest
    with open(path) as f:
        for line in f:
            if line.strip():
                r = json.loads(line)
                latest[r["run_id"]] = r   # later supersedes earlier
    return latest


def key(rec: dict) -> tuple:
    c = rec["config"]
    return (c["mechanism"], c["weight_precision"], c["kv_cache_dtype"],
            rec["load"]["workload"], rec["load"]["concurrency"])


def main() -> None:
    runs = load()
    if not runs:
        print("No sweep results. Run: python -m specfp8.sweep --sweep sweeps/perf.yaml")
        return

    # Consistency guard: same concurrency must mean same request count.
    by_conc: dict[int, set[int]] = defaultdict(set)
    for r in runs.values():
        by_conc[r["load"]["concurrency"]].add(r["load"]["n_requests"])
    inconsistent = {c: sorted(v) for c, v in by_conc.items() if len(v) > 1}

    groups: dict[tuple, list[dict]] = defaultdict(list)
    for r in runs.values():
        groups[key(r)].append(r)

    OUT.mkdir(parents=True, exist_ok=True)
    L = [f"# Throughput by configuration and concurrency", "",
         f"*Generated by `analysis/perf_tables.py` from `results/sweep.jsonl` "
         f"at code `{sha()}`. Do not edit by hand.*", ""]

    if inconsistent:
        L += ["> **Warning — inconsistent request counts.** These concurrency "
              "levels contain measurements taken with different numbers of "
              "requests, so their repeats are not comparable:", ""]
        for c, counts in sorted(inconsistent.items()):
            L.append(f"> - concurrency {c}: n in {counts}")
        L.append("")

    L += ["> **Speculative rows carry an error term this table does not show.** "
          "Throughput for a speculative configuration varies 2.16x across "
          "boots while acceptance does not (findings/F020). Every cell below "
          "has three repeats from a SINGLE boot, so the spread shown is "
          "prompt variance within one boot and is silent about the dominant "
          "source of error. Non-speculative rows are unaffected (0.6% "
          "across-boot reproducibility).", "",
          "Mean of 3 repeats, +/- sample standard deviation. Repeats draw "
          "**different** prompts (seed offset by repeat), so the spread "
          "includes prompt-sampling variance, not just measurement noise -- "
          "it answers \"what would a different draw from GSM8K give?\" rather "
          "than \"how repeatable is this run?\".", "",
          "| mech | weights | kv | conc | n | tok/s | +/- | req/s | tau | acc |",
          "|---|---|---|---|---|---|---|---|---|---|"]

    def stat(vals):
        vals = [v for v in vals if v is not None]
        if not vals:
            return None, None
        return (statistics.mean(vals),
                statistics.stdev(vals) if len(vals) > 1 else 0.0)

    for k in sorted(groups):
        rs = groups[k]
        tok, tok_sd = stat([r["throughput"]["output_tokens_per_s"] for r in rs])
        rps, _ = stat([r["throughput"]["requests_per_s"] for r in rs])
        tau, _ = stat([(r.get("spec") or {}).get("tau") for r in rs])
        acc, _ = stat([r["task"]["accuracy"] for r in rs])
        n = rs[0]["load"]["n_requests"]
        pct = f"{tok_sd / tok * 100:.1f}%" if tok else "-"
        L.append(
            f"| {k[0]} | {k[1]} | {k[2]} | {k[4]} | {n} | {tok:.1f} | "
            f"{pct} | {rps:.3f} | {f'{tau:.2f}' if tau else '-'} | "
            f"{f'{acc:.1%}' if acc else '-'} |")

    # Scaling: what does concurrency actually buy, per configuration?
    L += ["", "## Throughput scaling with concurrency", "",
          "Ratio to that configuration's own concurrency-1 throughput. "
          "Perfectly linear scaling would give 4 / 16 / 64.", "",
          "| mech | weights | kv | c=1 tok/s | x4 | x16 | x64 |",
          "|---|---|---|---|---|---|---|"]
    cfgs = sorted({k[:3] for k in groups})
    for cfg in cfgs:
        base = stat([r["throughput"]["output_tokens_per_s"]
                     for r in groups.get((*cfg, "gsm8k", 1), [])])[0]
        if not base:
            continue
        row = [f"| {cfg[0]} | {cfg[1]} | {cfg[2]} | {base:.1f} "]
        for c in (4, 16, 64):
            v = stat([r["throughput"]["output_tokens_per_s"]
                      for r in groups.get((*cfg, "gsm8k", c), [])])[0]
            row.append(f"| {v / base:.1f}x " if v else "| - ")
        L.append("".join(row) + "|")

    (OUT / "throughput.md").write_text("\n".join(L) + "\n")
    print(f"  wrote analysis/out/tables/throughput.md ({len(groups)} cells)")
    if inconsistent:
        print(f"  WARNING inconsistent request counts at concurrency "
              f"{sorted(inconsistent)}")


if __name__ == "__main__":
    main()
